---
title: "Descriptive Text"
author: "Jackson DeCook"
date: "2025-12-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The source of this data was the Tidy Tuesday data set involving national park visitation rates and boundaries. National Park Service (NPS) data on deaths is also included to help answer questions about national park areas with many deaths, common causes of death, and age groups occur most frequently. 

The *Interactive Map* displays the total death counts at all national parks in the United States. Scroll to zoom in and hover over individual parks to find their attributed death count. The *Mortality Table* also displays individual park death counts, as well as the common age ranges and causes of death. Finally, users can select an *Interactive Bar Chart* from the cause of death drop-down menu to explore how deaths are distributed across age ranges. 

Interestingly, we found that of drowning deaths in national parks, many were within the 15-24 age range instead of the expected 0-14 age range. This is likely due to the heightened awareness and regulations surrounding drowning safety in children, while these are softened in teenagers and young adults. Also, other factors such as alcohol could affect the increase in drowning deaths in this age group.
